services:
  pwa:
    build:
      dockerfile: pwa.Dockerfile
      ssh:
        - default
      target: prod
      platforms:
        - linux/amd64
        #- linux/arm64

  api:
    build:
      dockerfile: api.Dockerfile
      ssh:
        - default
      target: prod
      platforms:
        - linux/amd64
        #- linux/arm64
