nelmio_api_doc:
    documentation:
        info:
            title: Wedding for Manuele & Robine
            description: API documentation for Wedding for Manuele & Robine
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
