nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['HEAD', 'OPTIONS', 'GET', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    # https://symfony.com/bundles/LexikJWTAuthenticationBundle/current/4-cors-requests.html#example-usage-with-the-lexikjwtauthenticationbundle
    #paths:
    #    '^/common/api/':
    #        allow_origin: ['*']
    #        allow_headers: ['*']
    #        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
    #        max_age: 3600
    #    '^/admin/api/':
    #        allow_origin: ['*']
    #        allow_headers: ['*']
    #        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
    #        max_age: 3600
